ui:
  stl: feline
  bfl: bufferline
  tree: chadtree

autocomplete:
  framework: coq
  snippets: null
  lsp: true

plugins:
  - 'tpope/vim-commentary'
  - 'tiagovla/tokyodark.nvim'
  - 'windwp/nvim-autopairs'

options:
  mouse: a
  relativenumber: true
  number: true
  clipboard: unnamedplus
  timeoutlen: 500
  shiftwidth: 4
  splitbelow: true
  splitright: true
  autoindent: true
  smartindent: true
  breakindent: true
  copyindent: true
  expandtab: true
  cursorline: true
  cursorlineopt: number
  cmdheight: 2
  hlsearch: false
  ruler: true
  scrolloff: 10
  confirm: true
  winblend: 10
  wrap: false

colorscheme: tokyodark

variables:
  tokyodark_transparent_background: false
  tokyodark_enable_italic: true
  tokyodark_enable_italic_comment: true
  tokyodark_color_gamma: "0.9"
